services:
  db:
    image: postgres:17-alpine
    container_name: postgres_ca_nodejs
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ca_nodejs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ca_nodejs_network

  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ca_nodejs:0.0.8
    container_name: ca_nodejs
    ports:
      - '3000:3000'
    env_file:
      - dev.env
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - ca_nodejs_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - '80:80'
    depends_on:
      - app_dev
    networks:
      - ca_nodejs_network

networks:
  ca_nodejs_network:
    driver: bridge

volumes:
  postgres_data:
